### ISSUE TITLE
License for the repository

### ISSUE THREAD

**Issue by ConjuringCoffee** [alwinvandeput/zcx_return3#5]
Hi Alwin,

This repository doesn't contain a license yet. This means that nobody has permission from you to use, modify, or share the code in the repository. ([See Github's explanation here.](https://choosealicense.com/no-permission/)) Do you have any plans to add a license in the near future? 

Thank you.

**Comment by ConjuringCoffee** [comment]
Hi Alwin,
Unfortunately I didn't get a reaction from you yet. What are your thoughts on the matter? 
Me and my colleagues of a medium-sized business would like to use your framework commercially. We are currently under time pressure, so if we don't receive an answer during this week, we'd be forced to look for an alternative.

Thank you.

**Comment by alwinvandeput** [comment]
Hello,

I'm very busye for a client of mine and I do not have time to update this project.
I just added a license. I hope it helps you.

Kind regards, Alwin.

**Comment by ConjuringCoffee** [comment]
Thank you very much!
